# Generated by Django 5.2 on 2025-07-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_privetmassage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privetmassage',
            old_name='reciver',
            new_name='receiver',
        ),
    ]
